version: '3.7'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www
        depends_on:
            - php
            - mysql
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ../:/var/www
        depends_on:
            - mysql
            - redis
        environment:
            - PHP_FPM_INSTALL_NODE=true
        mem_limit: 512m  # Лимит памяти для контейнера PHP
    mysql:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    composer:
        image: composer:latest
        volumes:
            - .:/app
        command: composer install --ignore-platform-reqs
volumes:
    mysqldata:
